# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-21 17:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='file_type',
            field=models.CharField(default='mp3', max_length=100),
        ),
    ]
