# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-22 19:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_song_file_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='album_logo',
            field=models.FileField(default='', upload_to=''),
        ),
    ]
