# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-25 06:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, upload_to='blog/images'),
        ),
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.CharField(default='zoro', max_length=100),
        ),
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateField(),
        ),
    ]
