# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-25 07:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20160425_1451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.FileField(blank=True, upload_to='blog/images'),
        ),
    ]
